name: 'cPanel Deploy Action'
description: 'deploy to cPanel using cPanel API and git'
inputs:
  hostname:
    description: 'hostname of cPanel installation, including protocol. for instance: https://hostname.example.com'
    required: true
  cPanelApiPort:
    description: "Port of cPanel API. The default value is 2083 - don't change it unless you know what you're doing"
    required: false
    default: '2083'
  cpanel_token:
    description: "cPanel API token, used for authorization. You should store this as a repository-secret."
    required: true
  cpanel_username:
    description: "cPanel username used for API calls. Must be the same username used to create the token. e.g: 'joe'"
    required: true
  repository_root:
    description: "folder in which the repository is installed in the target cPanel account. must already exist. e.g: /home/your_account/repositories/your_repository"
    required: true
  updateRepository:
    description: "Whether or not to update the repository before triggering the deployment. If true - parameter 'branch' is required. defaults to 'true'."
    required: true
    default: 'true'
  branch:
    description: "branch to deploy. e.g: 'main' or 'master', or any other branch"
    required: false
    default: 'main'
outputs:
  duration:
    description: 'Duration of deployment, in milliseconds'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: arrow-up-right
  color: orange